title: Developer Docs
email: admin@lostlands.co
description: >-
  Official developer documentation for Lost Lands. Currently this documenation highlights the usage and implementation of Lost Lands API v1
baseurl: "/"
url: "https://developer.lostlands.co"
remote_theme: pmarsceill/just-the-docs

aux_links:
  "Lost Lands":
    - "https://lostlands.co/"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2020 Lost Lands. Official API written by Kore."
